### ISSUE TITLE
정렬쓰 이슈

### ISSUE THREAD

**Issue by jsh-me** [DDD-4/4servings-android#16]
### 요약

* 앱 설치 후 최초 접속시 가이드된 디자인이 아닌 최근항목 폴더가 생기는 이슈를 수정합니다.
* 폴더 생성시 정렬 순서를 변경합니다.

### 레이아웃

*  최초 사용자 홈 진입 시
<img src="https://user-images.githubusercontent.com/39688690/93001140-ecb5de80-f567-11ea-87a7-2ffe8c232ae1.png" width=300> 

* 폴더 추가 시 정렬 순서 
<img src="https://user-images.githubusercontent.com/39688690/93001147-f5a6b000-f567-11ea-86a2-5c028e893d4b.png" width=300>

**Comment by peterchoee** [comment]
@jsh-me 
수정하면서 이미지 캡쳐 이름이 중복되는 현상이 있어서 함께 수정했습니다~
