### ISSUE TITLE
세희쓰 이슈

### ISSUE THREAD

**Issue by jsh-me** [DDD-4/4servings-android#17]
### 요약

* 아이템이 없을 때 최근순, 버리는 순을 제거합니다.
* 아이템 선택 시 사진을 불러옵니다.
* 아이템 삭제 시 알람매니저에 등록한 알람을 삭제합니다.
* 폴더로 이동시 선택했던 아이템을 해제합니다.

### 레이아웃

* 최신순, 버리는순
<img src="https://user-images.githubusercontent.com/39688690/93001224-8a111280-f568-11ea-851a-73225b121e55.png" width=300>

* 아이템 선택 시 사진 불러오기
<img src="https://user-images.githubusercontent.com/39688690/93001232-9dbc7900-f568-11ea-85da-8ad75c925375.png" width=300>

* 취소버튼 시 선택 해제
<img src="https://user-images.githubusercontent.com/39688690/93001378-96499f80-f569-11ea-952d-f8df56b9605f.png" width=300>

**Comment by peterchoee** [comment]
빠르게 부탁드려요 ^^
