### ISSUE TITLE
아이템 추가 화면 디자인 수정

### ISSUE THREAD

**Issue by jsh-me** [DDD-4/4servings-android#34]
### 요약

**where** 
사용자가 아이템을 등록할 때 나오는 페이지

* 카테고리 아이템을 추가합니다.
* 서브 카테고리 디자인을 수정합니다.

### 레이아웃

|Before|After|
|:---:|:---:|
|<img src ="https://user-images.githubusercontent.com/39688690/94358534-c30ac480-00dc-11eb-9557-cbad0e0b86f9.png" width="300">|<img src ="https://user-images.githubusercontent.com/39688690/94358511-98207080-00dc-11eb-9fa2-09a8ee38cd5f.png" width="300">|

**Comment by jsh-me** [comment]
@choedeb 선생님 디자인 수정 작업이 전부 진행되지 않았습니다~!!!! 대분류 카테고리 안 이미지 확인 부탁드림~🙏

**Comment by peterchoee** [comment]
> @choedeb 선생님 디자인 수정 작업이 전부 진행되지 않았습니다~!!!! 대분류 카테고리 안 이미지 확인 부탁드림~🙏

@jsh-me 다른 전체 카테고리에 대한 아이콘이 없고 디자인상 3개 밖에 없는데 이부분 적용하나요?? 초기부터 제가 말씀드린 사항인데 ㅠㅠ
